### ISSUE TITLE
Incorrect response MIME type. Expected 'application/wasm'.

### ISSUE THREAD

**Issue by jshbrntt** [ianjsikes/rust-wasm-loader#2]
When I load my project I get the following warning.
```
wasm streaming compile failed: TypeError: Incorrect response MIME type. Expected 'application/wasm'.
```

Is there a way to fix this?

**Comment by evilfer** [comment]
This is not a problem with the loader, but with the http-server module used for testing. I can't find a way of configuring mime types for 'http-server', but it can be done with 'local-web-server'

I solved this with:
```
npm i local-web-server
```

Create a file ```lws.config.js```:
```
module.exports = {
    mime: {
        'application/wasm': ['wasm']
    }
};
```

Then update ```package.json```
```
"scripts": {
    ...
    "serve": "ws"
  },
```
