### ISSUE TITLE
How to exchange data between JS and rust

### ISSUE THREAD

**Issue by evilfer** [ianjsikes/rust-wasm-loader#3]
The example shows how to send and receive numbers. Is it possible to exchange Rust structs as well?

**Comment by ianjsikes** [comment]
Currently, there isn't a clean, efficient way to do this that I know of. That should improve eventually. You can accomplish it by (de)serializing data structures to and from JSON strings using the [serde_json][1] crate.

At this point, I would recommend [stdweb][2] for anything non-trivial using Rust on the web.

[1]: https://github.com/serde-rs/json
[2]: https://github.com/koute/stdweb

**Comment by evilfer** [comment]
Thanks, I'll check that stdweb, it looks very interesting (I imagine is not compatible with rust-wasm-loader?). Also [neon](https://www.neon-bindings.com//) seems to provide a mechanism to exchange data, though as far as I can see it doesn't allow invoking JS from Rust, like stdweb does.

Thank you!
