### ISSUE TITLE
Be able to load lib.rs

### ISSUE THREAD

**Issue by greenpdx** [ianjsikes/rust-wasm-loader#4]
I am trying to build a lib.rs module. I am using stdweb (https://github.com/koute/stdweb) The build creates a lib + PACKAGENAME in wasm32-unknown-unknown directory with extensions .f, .rlib, .wasm
.  
My webpack skills are not good enough to be much help. I am looking at https://github.com/ballercat/wasm-loader for the wasm loader.
and it uses cargo-web
I will be playing with it for a while, any help would be appreciated

**Comment by greenpdx** [comment]
Hi  I have looked at rust-native-wasm-loader and this loader.  
I added 

[lib]
crate-type = ["cdylib"]

and  I am using 
cargo web  build --target=wasm32-unknown-unknown
 to build.

Now I can use a lib.rs.

Now I am trying to load it into a Vue component.  So you example of using promise or async do not work because there is Vue component wrapper magic. 
How would I load the Module, and use it like an standard import?

I am willing to code it but I need some help getting started.

https://stackoverflow.com/questions/48735713/load-a-rust-wasm-library-into-vue-component-es6

**Comment by ianjsikes** [comment]
#10 might have solved this. Give it a shot.

**Comment by greenpdx** [comment]
I will try it.

**Comment by germania** [comment]
@greenpdx Using `vue-loader`, `stdweb` and this project, attached vue SFC works for me
[RustTest.vue.txt](https://github.com/ianjsikes/rust-wasm-loader/files/2120306/RustTest.vue.txt)
