### ISSUE TITLE
Rust loader does not copy over the wasm file from the target directory correctly

### ISSUE THREAD

**Issue by benkonz** [ianjsikes/rust-wasm-loader#5]
![image](https://user-images.githubusercontent.com/18561476/37912105-f2950c76-3111-11e8-9ed8-8f96e2fe09a3.png)

As you can see from the screenshot, `rust-wasm-webpack-template.wasm` and `rust_wasm_webpack_template.wasm` have different filenames, but are the same file. For some reason, the filenames change during the webpack build process and it is causing errors because the web assembly module does not know where the web assembly file is and this causes errors.

**Comment by benkonz** [comment]
fixed here: https://github.com/ianjsikes/rust-wasm-loader/pull/7

**Comment by ianjsikes** [comment]
Try it without emscripten now that #10 has been merged. Should solve your problem.
