### ISSUE TITLE
Add support for target wasm32-unknown-unknown

### ISSUE THREAD

**Issue by peerhenry** [ianjsikes/rust-wasm-loader#8]
As a developer I would like to have the option of choosing the wasm32-unknown-unknown target.
https://github.com/rust-lang/rust/pull/45905

**Comment by germania** [comment]
I have a working version of this as of last night, the boilerplate is actually way cleaner... Have to clean things up but I'm hoping to submit a PR this weekend

**Comment by germania** [comment]
Added in https://github.com/ianjsikes/rust-wasm-loader/pull/10

**Comment by ianjsikes** [comment]
@peerhenry `wasm32-unknown-unknown` support is merged in. Great work @germania .
